### ISSUE TITLE
Load Cells | Info

### ISSUE THREAD

**Issue by SeniaPiii** [robproject/lre-sendes#13]
Compression Load Cell
- Compression Force converted to weight number

Tension Load Cell
- Tension force converted to weight number

> Both
>- Accuracy of  +- 0.1%

![Screenshot 2023-08-30 135812](https://github.com/robproject/lre-sendes/assets/143038419/cf6ecdfd-0a55-4c3a-9ab7-2b53f5568e50)
Figure: Relationship between Volts and Weight

Equation: 
Cf = (slope of the above) x (Load Cell Calibration Factor Assumption)
    = N/kg
> Where         Cf = calibration factor
> & Assumption = given

**Comment by Abe2065** [comment]
[100lb load tension load cell $495 ](https://www.flintec.com/weight-sensors/force-sensors/miniature/isb)

[Specsheet](https://www.flintec.com/media/datasheets/isb-datasheet-en.pdf)

.1% accuary
