### ISSUE TITLE
Water Filter

### ISSUE THREAD

**Issue by SeniaPiii** [robproject/lre-sendes#14]
Water system filter

**Comment by Abe2065** [comment]
[Filter with 3/8 in hose](https://www.amazon.com/AQUACREST-Filtration-Connect-Certified-Capacity/dp/B089D156HL/ref=sr_1_25?crid=MIDF000IAIAX&keywords=Under+Sink+Water+Filter+System&qid=1693379564&refinements=p_85%3A2470955011&rnid=2470954011&rps=1&s=hi&sprefix=under+sink+water+filter+system%2Ctools%2C179&sr=1-25)

[Hose to 3/8 in fitiing $6.65 ](https://www.homedepot.com/p/Everbilt-3-4-in-FHT-x-3-8-in-OD-Compression-90-Degree-Brass-Elbow-Adapter-Fitting-801199/207176797)

[Valve for pressure vessel $10.78](https://www.homedepot.com/p/BrassCraft-3-8-in-Female-Compression-Inlet-x-3-8-in-Compression-Outlet-1-4-Turn-Straight-Ball-Valve-KTCR11FX-C1/203309315?source=shoppingads&locale=en-US&pla&mtc=SHOPPING-BF-CDP-GGL-D26P-026_001_PIPE_FITTING-NA-NA-NA-PMAX-NA-NA-NA-NA-NBR-NA-NA-NEW-PMax&cm_mmc=SHOPPING-BF-CDP-GGL-D26P-026_001_PIPE_FITTING-NA-NA-NA-PMAX-NA-NA-NA-NA-NBR-NA-NA-NEW-PMax-71700000097492030--&gclid=Cj0KCQjw0bunBhD9ARIsAAZl0E1UWK65R7876CcnOMQXNEnzAEJI9LEivTJ2e3gtIAA-T85-gI9VA_kaApLoEALw_wcB&gclsrc=aw.ds)
