### ISSUE TITLE
TRR Subscale Data

### ISSUE THREAD

**Issue by SeniaPiii** [robproject/lre-sendes#22]
Work:
- Find Reynold's number
- Calculate Data expected
- Create a checklist with expectations

Answer these questions:
- What to do when troubleshooting issues
- How will parts get assembled
- What data are we comparing to full-scale test run

Completed When:
- Resubmitted to Professors

**Comment by robproject** [comment]
On first application start, [this method](https://github.com/robproject/lre-sendes/blob/f44bf0ae037f146d72a5f59465f41b980e80a13f/sendes/app/services.py#L557) generates sample data for a simulated test with a Cd of 0.6, and saves it to the db as the first test. It's using the same uncertainty values as calculated in Matlab uncertainty propagation.
